### ISSUE TITLE
Detection of GOFIGURE_DEBUG failes

### ISSUE THREAD

**Issue by zxchris** [ian-kent/gofigure#3]
https://github.com/ian-kent/gofigure/blob/master/gofigure.go#L21

Have fixed as below and will issue pull request at some point!

```golang
var _ = func() (_ struct{}) {
   ...
}()
```

**Comment by ian-kent** [comment]
awesome thanks, merged, and just updated that bit to use `func init() {}` instead

can't see how my version _ever_ worked 😞
