### ISSUE TITLE
Cannot get application using gofigure to work with tests/goconvey

### ISSUE THREAD

**Issue by zxchris** [ian-kent/gofigure#6]
Have added `test.v` and `test.timeout` to application `struct{}` to get tests working, but is a bit ugly. However test parameter `-convey-json` is causing grief as it is supplied by goconvey without a parameter, and gofigure *expects* a parameter, even if the flag is `bool`. golang `flag` does not expect a parameter.

Not resolved the problem yet. Any help would be appreciated.

It might be nice to automatically accept the known test parameters in gofigure, if running in test mode (or not complain if a command line flag is given that is not declared).

**Comment by ian-kent** [comment]
Hm, I _think_ I'm following what you mean 😸 

It looks like gofigure's behaviour is incorrect, a bool flag without a var should be treated as `true` to match the standard library flag package, i.e. these are (should be!) functionally equivalent:

```
app -bool-flag
app -bool-flag=true
```

would correcting that behaviour fix the problem?

if i've completely misunderstood, any chance you could provide a golfed example of a failing goconvey test?

**Comment by zxchris** [comment]
That would fix the immediate problem, allowing me to work around an underlying issue I'm scratching my head about....

I've swapped the config handling in an app from using `flag` directly to using `gofigure` (for ref it's ERIC!). Now the app complains about all the flags passed in when running unit tests and `goconvey`. The *workaround* is to add `-test.v` `-test.timeout` `-convey-json` as declared (but ignored) flags in the app. I don't know if there are any others I will need to add, until I can get past `-convey-json`. Having to add all these flags to get unit tests to run is messy...

I guess the underlying question is, why does using `flag` directly not have any issue with the test flags, and using `gofigure` does?

**Comment by zxchris** [comment]
I'll concoct a test for you ;-)

**Comment by ian-kent** [comment]
> I guess the underlying question is, why does using flag directly not have any issue with the test flags, and using gofigure does?

It looks like Go's `testing` package does some flag parsing of its own:
https://golang.org/cmd/go/#hdr-Description_of_testing_flags

And GoConvey adds some flags to that:
https://github.com/smartystreets/goconvey/blob/5db88ed452e937f2fd557de6f4f1af7f2eabed0b/convey/init.go#L21

Gofigure doesn't respect any pre-defined flags and resets them on initialisation, which I think happens here:
https://github.com/ian-kent/gofigure/blob/469c386f6a66a8a56908b83020918425e6604853/sources/commandline.go#L47

So even if flag handling isn't compatible with the `flag` package, that line probably shouldn't be resetting any existing flags set before gofigure is called anyway!

Probably a couple of fixes I need to do there 👍

**Comment by zxchris** [comment]
Okay. Removing the creation of a new CommandLine parser (line 47) pretty much fixes things.

I get *"flag provided but not defined: -test.v"* spat out (at least when using `goconvey`) which is unexpected, and I can't figure out why.
